allow_fail:
- env: BUILDVARIANT=maemo.armel
- env: BUILDVARIANT=coverage
- env: BUILDVARIANT=uwp.amd64
- env: BUILDVARIANT=uwp.arm
- env: BUILDVARIANT=steam.amd64
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
coverage: false
display_name: Coffee Imgui
makefile_location: toolchain/makers
name: CoffeeImGui
platforms:
  android:
  - armv7a.kitkat.gles2
  - armv8a.nougat.gles3
  emscripten:
  - wasm
  fedora:
  - amd64
  ios:
  - x86_64
  osx:
  - .
  steam:
  - amd64
  ubuntu:
  - amd64
  uwp:
  - amd64
  win32:
  - amd64
script_location: toolchain/ci
secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
template_location: cmake/Templates
version:
  hotfix: 1
  major: 0
  minor: 9
  patch: 5
  release: 11
versionprefix: v
