allow_fail:
- env: BUILDVARIANT=maemo.armel
- env: BUILDVARIANT=coverage
- env: BUILDVARIANT=uwp.amd64
- env: BUILDVARIANT=uwp.arm
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
coverage: false
dependencies:
  hbirchtree/coffeecutie: automated-release-4.3.0.0.1
display_name: Coffee Imgui
makefile_location: toolchain/makers
name: CoffeeImGui
platforms:
  android:
  - armv7a.kitkat.gles2
  - armv8a.nougat.gles3
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  osx:
  - osx
  - ios.x86_64
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: toolchain/ci
secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
template_location: cmake/Templates
version:
  hotfix: 0
  major: 0
  minor: 9
  patch: 0
  release: 10
versionprefix: v
