branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
coverage: true
dependencies:
  hbirchtree/coffeecutie: automated-release-2.4.2
display_name: Coffee Imgui
exports:
  COFFEE_IMGUI_INCLUDE_DIR:
    file: imgui_binding.h
    path: coffee/imgui
    required: true
    type: header
  COFFEE_IMGUI_LIBRARY:
    file: CoffeeImGui
    required: true
    type: library
makefile_location: ci
name: CoffeeImGui
platforms:
  android:
  - armv7a
  - armv8a
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  maemo:
  - armel
  osx:
  - osx
  - ios.x86_64
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: ci
template_location: cmake/Templates
