branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
coverage: true
dependencies:
  hbirchtree/coffeecutie: automated-release-2.4.1-1-ge5c6140
display_name: Coffee Imgui
makefile_location: ci
name: coffeeimgui
platforms:
  android:
  - armv7a
  - armv8a
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  maemo:
  - armel
  osx:
  - osx
  - ios.x86_64
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: ci
template_location: cmake/Templates
