before_script:
- ci/install-dependencies.sh
branches:
  only:
  - master
  - testing
compiles:
- clang
deploy:
  api_key: ${GITHUB_TOKEN}
  file: libraries_$BUILDVARIANT.tar.gz
  'on':
    branch: master
  provider: releases
  skip_cleanup: true
dist: trusty
env:
  global:
  - MAKEFILE_DIR=ci
  - DEPENDENCIES=github:hbirchtree/coffeecutie:unstable;
  matrix:
  - BUILDVARIANT=android.armv7a
  - BUILDVARIANT=android.armv7a.kitkat
  - BUILDVARIANT=android.armv8a
  - BUILDVARIANT=emscripten.asmjs
  - BUILDVARIANT=emscripten.wasm
  - BUILDVARIANT=fedora.amd64
  - BUILDVARIANT=maemo.armv7a
  - BUILDVARIANT=raspberry.armhf
  - BUILDVARIANT=steam.amd64
  - BUILDVARIANT=ubuntu.amd64
  - BUILDVARIANT=ubuntu.i686
  - BUILDVARIANT=osx
language: cpp
matrix:
  exclude:
  - env: BUILDVARIANT=android.armv7a
    os: osx
  - env: BUILDVARIANT=android.armv7a.kitkat
    os: osx
  - env: BUILDVARIANT=android.armv8a
    os: osx
  - env: BUILDVARIANT=emscripten.asmjs
    os: osx
  - env: BUILDVARIANT=emscripten.wasm
    os: osx
  - env: BUILDVARIANT=fedora.amd64
    os: osx
  - env: BUILDVARIANT=maemo.armv7a
    os: osx
  - env: BUILDVARIANT=raspberry.armhf
    os: osx
  - env: BUILDVARIANT=steam.amd64
    os: osx
  - env: BUILDVARIANT=ubuntu.amd64
    os: osx
  - env: BUILDVARIANT=ubuntu.i686
    os: osx
  - env: BUILDVARIANT=osx
    os: linux
os:
- linux
- osx
script:
- ci/build.sh
services:
- docker
sudo: required
