after_success:
- toolchain/ci/travis-deploy.sh
apt:
  update: true
before_script:
- toolchain/ci/travis-deps.sh
branches:
  only:
  - master
  - testing
compiles:
- clang
dist: trusty
env:
  global:
  - MAKEFILE_DIR=toolchain/makers
  - DEPENDENCIES=hbirchtree/coffeecutie%
  - CONFIGURATION=Release
  matrix:
  - BUILDVARIANT=android.armv7a.kitkat.gles2
  - BUILDVARIANT=android.armv8a.nougat.gles3
  - BUILDVARIANT=emscripten.wasm
  - BUILDVARIANT=fedora.amd64
  - BUILDVARIANT=steam.amd64
  - BUILDVARIANT=ubuntu.amd64
  - BUILDVARIANT=ios.x86_64
  - BUILDVARIANT=osx
language: cpp
matrix:
  allow_failures:
  - env: BUILDVARIANT=maemo.armel
  - env: BUILDVARIANT=coverage
  - env: BUILDVARIANT=uwp.amd64
  - env: BUILDVARIANT=uwp.arm
  exclude:
  - env: BUILDVARIANT=android.armv7a.kitkat.gles2
    os: osx
  - env: BUILDVARIANT=android.armv8a.nougat.gles3
    os: osx
  - env: BUILDVARIANT=emscripten.wasm
    os: osx
  - env: BUILDVARIANT=fedora.amd64
    os: osx
  - env: BUILDVARIANT=steam.amd64
    os: osx
  - env: BUILDVARIANT=ubuntu.amd64
    os: osx
  - env: BUILDVARIANT=ios.x86_64
    os: linux
  - env: BUILDVARIANT=osx
    os: linux
notifications:
  email: true
os:
- linux
- osx
script:
- toolchain/ci/travis-build.sh
services:
- docker
sudo: required
