before_script:
- ci/travis-deps.sh
branches:
  only:
  - master
  - testing
compiles:
- clang
deploy:
  api_key: ${GITHUB_TOKEN}
  file: libraries_$BUILDVARIANT.tar.gz
  'on':
    branch: master
  provider: releases
  skip_cleanup: true
dist: trusty
env:
  global:
  - MAKEFILE_DIR=ci
  - DEPENDENCIES=hbirchtree/coffeecutie;
  matrix:
  - android.armv7a
  - android.armv7a.kitkat
  - android.armv8a
  - emscripten.asmjs
  - emscripten.wasm
  - fedora.amd64
  - maemo.armv7a
  - raspberry.armhf
  - steam.amd64
  - ubuntu.amd64
  - ubuntu.i686
  - ios
  - osx
group: deprecated-2017Q2
language: cpp
matrix:
  exclude:
  - env: android.armv7a
    os: osx
  - env: android.armv7a.kitkat
    os: osx
  - env: android.armv8a
    os: osx
  - env: emscripten.asmjs
    os: osx
  - env: emscripten.wasm
    os: osx
  - env: fedora.amd64
    os: osx
  - env: maemo.armv7a
    os: osx
  - env: raspberry.armhf
    os: osx
  - env: steam.amd64
    os: osx
  - env: ubuntu.amd64
    os: osx
  - env: ubuntu.i686
    os: osx
  - env: ios
    os: linux
  - env: osx
    os: linux
os:
- linux
- osx
script:
- ci/travis-build.sh
services:
- docker
sudo: required
