branches:
  only:
  - master
  - testing
build_script:
- ps: ci\appveyor-build.ps1
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git
    %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
configuration:
- Debug
deploy_script:
- ps: ci\appveyor-deploy.ps1
environment:
  BUILDVARIANT: win32.amd64
  BUILD_DIR: C:\project\%APPVEYOR_PROJECT_SLUG%
  CMAKE_BIN: C:\Program Files\CMake\bin\cmake.exe
  DEPENDENCIES: hbirchtree/coffeecutie;
  DEPLOY_PATTERNS: ''
  GITHUB_TOKEN:
    secure: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
  MAKEFILE_DIR: ci
install:
- ps: ci\appveyor-deps.ps1
platform: x64
skip_tags: true
version: '{build}'
