branches:
- build: true
  deploy: true
  name: master
- build: true
  name: testing
dependencies:
- github:hbirchtree/coffeecutie:unstable
display_name: Coffee Imgui
engine_version: Appveyor-Build-529-3-g9368dfd
makefile_location: ci
name: coffeeimgui
platforms:
  android:
  - armv7a
  - armv8a
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  maemo:
  - armv7a
  osx:
  - osx
  - ios
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: ci
template_location: cmake/Templates
