
#
# Autogenerated by generate_project.py
# Changes made to this file will NOT be saved
# This find-script will make it easier to add several libraries for external use 
#

set ( COFFEE_SEARCH_PATHS
    /usr/local
    /usr
    /opt

    ~/Library/Frameworks
    /Library/Frameworks

    ${COFFEE_ROOT_DIR}
    $ENV{COFFEE_ROOT_DIR}
    )
set ( COFFEE_LIBRARY_SUFFIXES
    lib
    lib64
    lib/${ANDROID_ABI}
    lib/${CMAKE_LIBRARY_ARCHITECTURE}
    )

    
find_library ( COFFEE_IMGUI_LIBRARY_TMP
    CoffeeImGui
    
    PATHS ${COFFEE_SEARCH_PATHS}
    PATH_SUFFIXES ${COFFEE_LIBRARY_SUFFIXES}
    )

if(COFFEE_IMGUI_LIBRARY_TMP)
    set ( COFFEE_IMGUI_LIBRARY "${COFFEE_IMGUI_LIBRARY_TMP}" CACHE PATH "" )
endif()

find_path ( COFFEE_IMGUI_INCLUDE_DIR_TMP
    coffee/imgui/imgui_binding.h

    PATHS
    ${COFFEE_SEARCH_PATHS}

    PATH_SUFFIXES
    include
    )

if(COFFEE_IMGUI_INCLUDE_DIR_TMP)
    set ( COFFEE_IMGUI_INCLUDE_DIR "${COFFEE_IMGUI_INCLUDE_DIR_TMP}" CACHE PATH "" )
endif()

find_package_handle_standard_args (
    CoffeeImGui

    REQUIRED_VARS
COFFEE_IMGUI_LIBRARY
COFFEE_IMGUI_INCLUDE_DIR

    )
